# Generated by Django 3.2 on 2021-04-17 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=500, verbose_name="Текст поста")),
                ("date_of_post", models.DateField(verbose_name="Дата публикации")),
                (
                    "vk_id",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="ID сообщения из VK"
                    ),
                ),
                ("url", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="", verbose_name="Картинка поста"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="parsing.post",
                        verbose_name="Id поста",
                    ),
                ),
            ],
        ),
    ]
